//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterMonitor.TwitterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestInfo", Namespace="http://schemas.datacontract.org/2004/07/TwitterWCFService")]
    [System.SerializableAttribute()]
    public partial class RequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberTweetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackWordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberTweets {
            get {
                return this.NumberTweetsField;
            }
            set {
                if ((this.NumberTweetsField.Equals(value) != true)) {
                    this.NumberTweetsField = value;
                    this.RaisePropertyChanged("NumberTweets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackWord {
            get {
                return this.TrackWordField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackWordField, value) != true)) {
                    this.TrackWordField = value;
                    this.RaisePropertyChanged("TrackWord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StreamFaultInfo", Namespace="http://schemas.datacontract.org/2004/07/TwitterWCFService")]
    [System.SerializableAttribute()]
    public partial class StreamFaultInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwitterMonitor.TwitterService.RequestInfo RequestInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwitterMonitor.TwitterService.RequestInfo RequestInfo {
            get {
                return this.RequestInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestInfoField, value) != true)) {
                    this.RequestInfoField = value;
                    this.RaisePropertyChanged("RequestInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestData", Namespace="http://schemas.datacontract.org/2004/07/TwitterWCFService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwitterMonitor.TwitterService.PicturesData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwitterMonitor.TwitterService.SentimentData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwitterMonitor.TwitterService.HashtagsCountData))]
    public partial class RequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackWordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndedAt {
            get {
                return this.EndedAtField;
            }
            set {
                if ((this.EndedAtField.Equals(value) != true)) {
                    this.EndedAtField = value;
                    this.RaisePropertyChanged("EndedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackWord {
            get {
                return this.TrackWordField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackWordField, value) != true)) {
                    this.TrackWordField = value;
                    this.RaisePropertyChanged("TrackWord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PicturesData", Namespace="http://schemas.datacontract.org/2004/07/TwitterWCFService")]
    [System.SerializableAttribute()]
    public partial class PicturesData : TwitterMonitor.TwitterService.RequestData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwitterMonitor.TwitterService.TweetPictureData[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwitterMonitor.TwitterService.TweetPictureData[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SentimentData", Namespace="http://schemas.datacontract.org/2004/07/TwitterWCFService")]
    [System.SerializableAttribute()]
    public partial class SentimentData : TwitterMonitor.TwitterService.RequestData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NegativeWordsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwitterMonitor.TwitterService.WordCount[] NegativeWordsListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositiveWordsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwitterMonitor.TwitterService.WordCount[] PositiveWordsListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NegativeWordsCount {
            get {
                return this.NegativeWordsCountField;
            }
            set {
                if ((this.NegativeWordsCountField.Equals(value) != true)) {
                    this.NegativeWordsCountField = value;
                    this.RaisePropertyChanged("NegativeWordsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwitterMonitor.TwitterService.WordCount[] NegativeWordsList {
            get {
                return this.NegativeWordsListField;
            }
            set {
                if ((object.ReferenceEquals(this.NegativeWordsListField, value) != true)) {
                    this.NegativeWordsListField = value;
                    this.RaisePropertyChanged("NegativeWordsList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositiveWordsCount {
            get {
                return this.PositiveWordsCountField;
            }
            set {
                if ((this.PositiveWordsCountField.Equals(value) != true)) {
                    this.PositiveWordsCountField = value;
                    this.RaisePropertyChanged("PositiveWordsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwitterMonitor.TwitterService.WordCount[] PositiveWordsList {
            get {
                return this.PositiveWordsListField;
            }
            set {
                if ((object.ReferenceEquals(this.PositiveWordsListField, value) != true)) {
                    this.PositiveWordsListField = value;
                    this.RaisePropertyChanged("PositiveWordsList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HashtagsCountData", Namespace="http://schemas.datacontract.org/2004/07/TwitterWCFService")]
    [System.SerializableAttribute()]
    public partial class HashtagsCountData : TwitterMonitor.TwitterService.RequestData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwitterMonitor.TwitterService.HashtagData[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwitterMonitor.TwitterService.HashtagData[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HashtagData", Namespace="http://schemas.datacontract.org/2004/07/TwitterWCFService")]
    [System.SerializableAttribute()]
    public partial class HashtagData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HashtagIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashtagWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TweetCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HashtagId {
            get {
                return this.HashtagIdField;
            }
            set {
                if ((this.HashtagIdField.Equals(value) != true)) {
                    this.HashtagIdField = value;
                    this.RaisePropertyChanged("HashtagId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashtagWord {
            get {
                return this.HashtagWordField;
            }
            set {
                if ((object.ReferenceEquals(this.HashtagWordField, value) != true)) {
                    this.HashtagWordField = value;
                    this.RaisePropertyChanged("HashtagWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TweetCount {
            get {
                return this.TweetCountField;
            }
            set {
                if ((this.TweetCountField.Equals(value) != true)) {
                    this.TweetCountField = value;
                    this.RaisePropertyChanged("TweetCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TweetPictureData", Namespace="http://schemas.datacontract.org/2004/07/TwitterWCFService")]
    [System.SerializableAttribute()]
    public partial class TweetPictureData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TweetIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PictureURL {
            get {
                return this.PictureURLField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureURLField, value) != true)) {
                    this.PictureURLField = value;
                    this.RaisePropertyChanged("PictureURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TweetId {
            get {
                return this.TweetIdField;
            }
            set {
                if ((this.TweetIdField.Equals(value) != true)) {
                    this.TweetIdField = value;
                    this.RaisePropertyChanged("TweetId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WordCount", Namespace="http://schemas.datacontract.org/2004/07/TwitterWCFService")]
    [System.SerializableAttribute()]
    public partial class WordCount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmotionWordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmotionWord {
            get {
                return this.EmotionWordField;
            }
            set {
                if ((object.ReferenceEquals(this.EmotionWordField, value) != true)) {
                    this.EmotionWordField = value;
                    this.RaisePropertyChanged("EmotionWord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="TwitterService.ITwitterService")]
    public interface ITwitterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITwitterService/InitStreamAndSaveData", ReplyAction="http://Microsoft.ServiceModel.Samples/ITwitterService/InitStreamAndSaveDataRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwitterMonitor.TwitterService.StreamFaultInfo), Action="http://Microsoft.ServiceModel.Samples/ITwitterService/InitStreamAndSaveDataStream" +
            "FaultInfoFault", Name="StreamFaultInfo", Namespace="http://schemas.datacontract.org/2004/07/TwitterWCFService")]
        TwitterMonitor.TwitterService.RequestInfo InitStreamAndSaveData(TwitterMonitor.TwitterService.RequestInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITwitterService/InitStreamAndSaveData", ReplyAction="http://Microsoft.ServiceModel.Samples/ITwitterService/InitStreamAndSaveDataRespon" +
            "se")]
        System.Threading.Tasks.Task<TwitterMonitor.TwitterService.RequestInfo> InitStreamAndSaveDataAsync(TwitterMonitor.TwitterService.RequestInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITwitterService/HashtagsFrequencyData", ReplyAction="http://Microsoft.ServiceModel.Samples/ITwitterService/HashtagsFrequencyDataRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://Microsoft.ServiceModel.Samples/ITwitterService/HashtagsFrequencyDataString" +
            "Fault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        TwitterMonitor.TwitterService.HashtagsCountData HashtagsFrequencyData(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITwitterService/HashtagsFrequencyData", ReplyAction="http://Microsoft.ServiceModel.Samples/ITwitterService/HashtagsFrequencyDataRespon" +
            "se")]
        System.Threading.Tasks.Task<TwitterMonitor.TwitterService.HashtagsCountData> HashtagsFrequencyDataAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITwitterService/Pictures", ReplyAction="http://Microsoft.ServiceModel.Samples/ITwitterService/PicturesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://Microsoft.ServiceModel.Samples/ITwitterService/PicturesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        TwitterMonitor.TwitterService.PicturesData Pictures(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITwitterService/Pictures", ReplyAction="http://Microsoft.ServiceModel.Samples/ITwitterService/PicturesResponse")]
        System.Threading.Tasks.Task<TwitterMonitor.TwitterService.PicturesData> PicturesAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITwitterService/Sentiment", ReplyAction="http://Microsoft.ServiceModel.Samples/ITwitterService/SentimentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://Microsoft.ServiceModel.Samples/ITwitterService/SentimentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        TwitterMonitor.TwitterService.SentimentData Sentiment(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITwitterService/Sentiment", ReplyAction="http://Microsoft.ServiceModel.Samples/ITwitterService/SentimentResponse")]
        System.Threading.Tasks.Task<TwitterMonitor.TwitterService.SentimentData> SentimentAsync(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITwitterServiceChannel : TwitterMonitor.TwitterService.ITwitterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwitterServiceClient : System.ServiceModel.ClientBase<TwitterMonitor.TwitterService.ITwitterService>, TwitterMonitor.TwitterService.ITwitterService {
        
        public TwitterServiceClient() {
        }
        
        public TwitterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwitterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwitterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwitterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TwitterMonitor.TwitterService.RequestInfo InitStreamAndSaveData(TwitterMonitor.TwitterService.RequestInfo data) {
            return base.Channel.InitStreamAndSaveData(data);
        }
        
        public System.Threading.Tasks.Task<TwitterMonitor.TwitterService.RequestInfo> InitStreamAndSaveDataAsync(TwitterMonitor.TwitterService.RequestInfo data) {
            return base.Channel.InitStreamAndSaveDataAsync(data);
        }
        
        public TwitterMonitor.TwitterService.HashtagsCountData HashtagsFrequencyData(string code) {
            return base.Channel.HashtagsFrequencyData(code);
        }
        
        public System.Threading.Tasks.Task<TwitterMonitor.TwitterService.HashtagsCountData> HashtagsFrequencyDataAsync(string code) {
            return base.Channel.HashtagsFrequencyDataAsync(code);
        }
        
        public TwitterMonitor.TwitterService.PicturesData Pictures(string code) {
            return base.Channel.Pictures(code);
        }
        
        public System.Threading.Tasks.Task<TwitterMonitor.TwitterService.PicturesData> PicturesAsync(string code) {
            return base.Channel.PicturesAsync(code);
        }
        
        public TwitterMonitor.TwitterService.SentimentData Sentiment(string code) {
            return base.Channel.Sentiment(code);
        }
        
        public System.Threading.Tasks.Task<TwitterMonitor.TwitterService.SentimentData> SentimentAsync(string code) {
            return base.Channel.SentimentAsync(code);
        }
    }
}
